api = "0.10"

[buildpack]
id = "heroku/dotnet"
version = "0.1.0"
name = "Heroku .NET"
homepage = "https://github.com/heroku/buildpacks-dotnet"
description = "Heroku's buildpack for .NET applications."
keywords = ["dotnet", ".NET", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

# [[stacks]] is deprecated in Buildpack API 0.10, but is (unintentionally?)
# required by `pack buildpack package`. The [[stacks]] table should be
# removed when the issue (https://github.com/buildpacks/pack/issues/2047) is
# resolved.
[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "arm64"

[[targets]]
os = "linux"
arch = "amd64"
