[package]
name = "inventory-updater"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
heroku-inventory-utils = { git = "https://github.com/heroku/buildpacks-go/", rev = "2a86fae18332b9bd495eb29422c13ac3fcb2d0dc" }
semver = "1.0"
serde = "1"
sha2 = "0.10"
toml = "0.8"
ureq = { version = "2", features = ["json"] }
