name: Update Inventory
on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * 1-5'

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-dotnet-inventory:
    name: Update .NET SDK inventory
    runs-on: pub-hk-ubuntu-24.04-ip
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ vars.LINGUIST_GH_APP_ID }}
          private-key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Update Rust toolchain
        run: rustup update

      - name: Rust cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - name: Rebuild Inventory
        id: rebuild-inventory
        run: cargo run --package inventory-updater buildpacks/dotnet/inventory.toml buildpacks/dotnet/CHANGELOG.md

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: "Update .NET Inventory"
          commit-message: "Update Inventory for heroku/dotnet"
          committer: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>
          author: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>
          branch: update-dotnet-inventory
          body: "Automated pull-request to update heroku/dotnet inventory"

      - name: Configure PR
        if: steps.pr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge --squash --auto "${{ steps.pr.outputs.pull-request-number }}"
